services:
  - type: web
    name: your-app-name
    env: python
    python:
      version: 3.12.7
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python app.py
